### PR TITLE
Eetom/frontend style

### PR DESCRIPTION
**Pull request by eetom**
For Review:

I'm using a bunch of placeholder code to simulate what the table and warning will look like.

here is a screenshot.

image

Feedback welcome!
I'll remove the excess code prior to approve/merge.

### CODE REVIEW

**Comment by eetom** [comment]
Table will have to have overflow for mobile/smaller screen views.
image

**Comment by eetom** [comment]
- Removed excess testing code
- Added back the footer
- Responsiveness fixed

Ready for review @Lekensteyn

**Comment by Lekensteyn** [comment]
I just tested it, it looks nice and clean. One bug: if the screen is resized to a smaller size, the footer is sticky to the bottom. When scrolling the page down, the footer moves up.

Though for now, this is a minor issue as mobile browsers are not yet supported by this test (which relies on Flash).

**Comment by Lekensteyn** [comment]
Thanks @eetom for the PR, I have applied it and also fixed the footer issue in 34d07b117464128e57976ea16199855547cc5cf6 (it would appear whenever the height it smaller, e.g. when devtools are open).

(Tested in Chrome only though)

**Pull request merged**
